#!/bin/bash
# chkconfig: 2345 95 20
# description: Starts and stops the rabbitcasa DAEMON
# processname: rabbitcasa

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0
DAEMON=/opt/scripts/rabbitcasa/rabbitcasa.py

status() {
	if [ -n "`pidofproc $DAEMON`" ] ; then
   		echo_success
        else
		echo_failure
	fi
	echo
}

start() {
	if [ -n "`pidofproc $DAEMON`" ] ; then
        	failure "Service already running"
        else
		python $DAEMON --start
        	sleep 3
		status
        fi
}

stop() {
	python $DAEMON --stop
        if [ -n "`pidofproc $DAEMON`" ] ; then
		failure "Service did not shut down cleanly"
                killproc $DAEMON
	fi
    	echo_success
	echo
}


# See how we were called.
case "$1" in
  start)
        start
	;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  status)
	status
	;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 1
