#!/bin/bash
# chkconfig: 2345 95 20
# description: Starts and stops the rabbitcasa DAEMON
# processname: rabbitcasa

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0
PYTHON=/usr/local/bin/python
SCRIPT=/opt/scripts/rabbitcasa/rabbitcasa.py
DAEMON=rabbitcasa

status() {
	if [ -n "`pidofproc $DAEMON`" ] ; then
   		echo -n "$DAEMON is running"
		echo_success
        else
		echo -n "$DAEMON is stopped"
		echo_success
	fi
}

start() {
	if [ -n "`pidofproc $DAEMON`" ] ; then
        	echo -n "Service already running"
		echo_failure
        else
		$PYTHON $SCRIPT --start
        	sleep 3
		status
        fi
}

stop() {
	$PYTHON $SCRIPT --stop
        if [ -n "`pidofproc $DAEMON`" ] ; then
		echo -n "Service did not shut down cleanly"
		echo_warning
                killproc $DAEMON
	fi
    	echo_success
}

# See how we were called.
case "$1" in
  start)
        start
	;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  status)
	status
	;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac
echo
exit 1
